# Generated by Django 4.2.3 on 2023-07-26 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eCommerce', '0002_alter_user_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(default='Not Approved', max_length=50),
        ),
    ]
